# Generated by Django 5.2.5 on 2025-08-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makequery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField(null=True)),
            ],
        ),
    ]
